---

 - name: install java 1.7
   yum: 
     name: java-1.7.0-openjdk-devel.x86_64 
     state: present
   sudo: yes

 - name: install unzip
   yum: 
     name: unzip
     state: present
   sudo: yes
   
 - name: create ansible directory
   file:
     path: /home/vagrant/ansible/
     state: directory
     mode: 0755

 - name: download jetty
   get_url: 
     url:  http://download.eclipse.org/jetty/9.2.15.v20160210/dist/jetty-distribution-9.2.15.v20160210.zip
     dest: "/home/vagrant/ansible/jetty-9.2.15.zip"
     
 - name: decompress package
   unarchive:
     src: /home/vagrant/ansible/jetty-9.2.15.zip
     dest: /home/vagrant/ansible/jetty-9.2.15

 - name: create ROOT directory
   file:
     path: /home/vagrant/ansible/jetty-9.2.5/webapps/ROOT
     state: directory
     mode: 0755

 - name: copy index.html
   copy: 
     src: index.html
     dest: /home/vagrant/ansible/jetty-9.2.5/webapps/ROOT

 - name: restart jetty
   shell: /home/vagrant/ansible/jetty-9.2.5/bin/jetty.sh restart
